### ISSUE TITLE
Header file `/gl/gl.h` was not found in production build

### ISSUE THREAD

**Issue by EmiyaSyahriel** [noxomix/vGL#3]
So, I am trying to compile my project for production build using this command :
```bash
v -prod -gc boehm_leak -cg .
```
But, I got this error:
```
builder error: Header file "/gl/gl.h", needed for module `noxomix.vgl` was not found. Please install the corresponding development headers.
```
Compiling for non-production build compiles and runs fine, though.

Also, compiling the provided `gears.v` example with the same command also failed with the same error. 
______________
Changing this line https://github.com/noxomix/vgl/blob/2a04bead129a2f144b91d47d389ee5333d9b59e9/implement.c.v#L5 to 
```c
#include "gl/gl.h"
```
_which I did by modifying the should-not-be-edited file in `~./vmodules`_, seems to remove the error. However, I am still not sure about this since my project still cannot be successfully compiled due to errors coming from other dependencies.

I am still learning V for past weekends coming from C/C++ background, therefore for me the `/gl/gl.h` seems like the code is trying to include the file `(system root)/gl/gl.h` instead of `(module root)/gl/gl.h`, But is it correct in V though?

## System Info
- OS : `Ubuntu 24.04 LTS x86_64 (6.8.0-31-generic)`
- V Version : `V 0.4.6 6d2c3a9`
- vGL Module Version : `0.0.1.1-experimental`
- OpenGL Version : `4.6.0`
- OpenGL ES Version : `3.2`
- GPU : `NVIDIA GeForce GTX 1060 6GB (proprietary driver 535.171.04)`

**Comment by noxomix** [comment]
Hello @EmiyaSyahriel , 

thanks for your Issue - Let me look into that. I'm currently not actively developing on it. 

I will get you to this soon and try to reproduce :)

Best Regards 
Theo

**Comment by noxomix** [comment]
Hello again, 

I've now fixed a few errors in the vgl project, including your input to change the `gl/gl.h` thing (thanks).

The other compiling errors happening are unfortunately in the vglfw of this other guy. I can try fix them but not today :c

Also take notice that the errors might happening are due my system defers from your system, and maybe i didnt fixed all the pointer casts, the Problem is that without the -prod -gc boehm... the compiler might accept that `const void **` are just can be `void **` - i fixed this by defining a new function which casts a void** to a const void** and put it into the binding callback. Only for the functions triggering errors for me. 

Special Notice - there might be an internal bug, or maybe I just dont know to fix so if you use the glStringi() function it can cause unexpected behavior/wrong pointer values. 

Since Im neither a C neither a V professional and this Project just was for myself (Im still wondering how I managed to create this library with this less knowledge :D) I cant answer you the question how its the V way. 

The Bug fixes are only applied into the `dev` branch - so instead in the .vmodules you install the library in an folder of your choice and do `import vgl` instead `import noxomix.vgl` to make sure to compile the right changed lib. To install use 
```
git clone --branch dev https://github.com/noxomix/vgl.git
```

I hope this can help you a bit. Best Regards Theo

**Comment by EmiyaSyahriel** [comment]
Thank you, the "missing header" compile error from this library seems to be resolved. And yes, the remaining error in my project is also mostly coming from vglfw too, I will make a new issue there regarding this after filtering my error logs.

So then, I will close this issue since it is resolved.

Once again, Thank you. 
Best regards, Syahriel.

**Comment by noxomix** [comment]
Good, but if there is any Compile error not coming from Vglfw ? Starting with `vgl__` or something, then please let me know I will try fix :) 

Also notice that the Vglfw maintainer is no longer developing on it and all current releases are pull requested from my fork so I will also try to fix Asap.
